displayName: JUIT GmbH / Fail2Ban
type: middleware
#iconPath: .assets/icon.png

import: github.com/juitde/traefik-plugin-fail2ban

summary: 'Block or allow IPs depending on various conditions (requires Traefik >= 2.10.0)'

testData:
  enabled: true
  alwaysAllowed:
    ip: "::1,127.0.0.1"
  alwaysDenied:
    ip: "192.168.0.0/24"
  logLevel: "INFO"
  rules:
    findTime: "10m"
    banTime: "3h"
    maxRetries: 4
    response:
      statusCodes: "400-401,403-499"
      errorCode: "403"
    abuseIpdb:
      enabled: true
      apiKey: "your-abuseipdb-api-key"
      confidenceThreshold: 75
      maxAgeInDays: 90
      timeout: "5s"
